#!/usr/bin/env bash

DOTFILES_VAR_DEBIAN='Debian'
DOTFILES_VAR_ARCH='Arch'

DOTFILES_VAR_SERVER='Server'
DOTFILES_VAR_DESKTOP='Desktop'

DOTFILES_VAR_ADMIN='Admin'
DOTFILES_VAR_USER='User'
DOTFILES_VAR_ROOT='Root'


# Excluded modules variables

DOTFILES_MOD_ZSH='zsh'
DOTFILES_MOD_BASH='bash'
DOTFILES_MOD_VIM='vim'
DOTFILES_MOD_UI='ui'
DOTFILES_MOD_MUSIC='music'
DOTFILES_MOD_SOUND='sound'
DOTFILES_MOD_VIDEO='video'
DOTFILES_MOD_TOOLS='tools'